libraries = [
  "arche",
  "hypogeios",
  "pelos",
  "speos"
]

[dev]
libraries = [
  "hypogeios_dev"
]
subagents = [
  "zork_src"
]

[author]
name = "sourcetrait"
title = "SourceTrait"
email = "development@sourcetrait.com"

[provider]
name = "github"
