name = "pelos"
title = "Pelos"
version = "0.0.0-1"

[nushell]
version = "0.113.1"

[description]
summary = "Shared substrate for the hypogeios suite: the cross-library locale loader."
keywords = []

[author]
name = "sourcetrait"
title = "SourceTrait"
email = "development@sourcetrait.com"

[license]
spdx = "agpl3"
file = "LICENSE-AGPL-3.txt"

[provider]
name = "github"
