name = "hypogeios"
title = "Hypogeios"
version = "0.0.9"

[nushell]
version = "0.113.1"

[description]
summary = "Classic preservation of classic terminal games written in Nu"
keywords = []

[author]
name = "sourcetrait"
title = "SourceTrait"
email = "development@sourcetrait.com"

[license]
spdx = "agpl3"
file = "LICENSE-AGPL-3.txt"

[provider]
name = "github"

[mcp]
calls = [
  "hypogeios:game:turn",
  "hypogeios:dev/repo:build"
]

[[bin]]
name = "play"

[dependencies]
arche = { provider = "github", author = "sourcetrait", path = "../arche" }
pelos = { provider = "github", author = "sourcetrait", path = "../pelos" }
speos = { provider = "github", author = "sourcetrait", path = "../speos" }
