# Code-gen typed in-code consts for arche (the derive_ layer; read source).
#
# Organizational, run-invoked only (NOT call() targets). Each derive_ fn takes a
# model_ record (the run-body orchestration composes them: `derive_engine
# (model_engine $wd) $od`), serializes it via `to nuon --list-of-records --indent 2`,
# and writes a generated-do-not-edit .nu carrying `export const NAME: <type> = <data>`
# - the strict typed const the engine spine loads at parse time. The const's type
# annotation mirrors the model_ return (the *_TYPE consts here, kept in sync by
# hand). Consume from a run() body: `use arche dev derive *`. (derive takes the
# record rather than calling model itself; cross-module composition is the
# run-body's job, not the library's.)

export const ENGINE_TYPE: string = "record<flags: table<snake: string, preserved: string, summary: string, state: oneof<nothing, record<default: bool, scope: list<string>>>>>"
export const WORLD_TYPE: string = "record<conditions: table<snake: string, kind: string>, rooms: table<snake: string, flags: list<string>, value: int, globals: list<string>, action: oneof<string, nothing>>, links: table<room: string, direction: string, target: string, conditions: list<oneof<string, nothing>>>, blocked: table<room: string, direction: string>>"

# Write <out_dir>/engine.nu = `export const ENGINE: <ENGINE_TYPE> = <data>`. Idempotent.
export def derive_engine [
    engine: record<flags: table<snake: string, preserved: string, summary: string, state: oneof<nothing, record<default: bool, scope: list<string>>>>>,
    out_dir: directory
]: nothing -> record<written: string, flags: int> {
    let data = ($engine | to nuon --list-of-records --indent 2)
    let header = "# generated by arche:dev:derive - do not edit"
    let body = ([$header "" $"export const ENGINE: ($ENGINE_TYPE) = ($data)" ""] | str join (char nl))
    let dir = ($out_dir | path join "engine")
    mkdir $dir
    let path = ($dir | path join "mod.nu")
    $body | save -f $path
    {written: $path, flags: ($engine.flags | length)}
}

# Write <out_dir>/<episode>/world.nu = `export const WORLD: <WORLD_TYPE> = <data>`. Idempotent.
export def derive_world [
    world: record<conditions: table<snake: string, kind: string>, rooms: table<snake: string, flags: list<string>, value: int, globals: list<string>, action: oneof<string, nothing>>, links: table<room: string, direction: string, target: string, conditions: list<oneof<string, nothing>>>, blocked: table<room: string, direction: string>>,
    episode: string,
    out_dir: directory
]: nothing -> record<written: string, rooms: int, links: int, blocked: int, conditions: int> {
    let data = ($world | to nuon --list-of-records --indent 2)
    let header = "# generated by arche:dev:derive - do not edit"
    let body = ([$header "" $"export const WORLD: ($WORLD_TYPE) = ($data)" ""] | str join (char nl))
    let dir = ($out_dir | path join $episode | path join "world")
    mkdir $dir
    let path = ($dir | path join "mod.nu")
    $body | save -f $path
    {written: $path, rooms: ($world.rooms | length), links: ($world.links | length), blocked: ($world.blocked | length), conditions: ($world.conditions | length)}
}
