# Code-gen typed in-code consts for arche (the derive_ layer; read source).
#
# Organizational, run-invoked only (NOT call() targets). Each derive_ fn takes a
# model_ record (the run-body orchestration composes them: `derive_engine
# (model_engine $wd) $od`), serializes it via `to nuon --list-of-records --indent 2`,
# and writes a generated-do-not-edit .nu carrying `export const NAME: <type> = <data>`
# - the strict typed const the engine spine loads at parse time. The const's type
# annotation mirrors the model_ return (the *_TYPE consts here, kept in sync by
# hand). Consume from a run() body: `use arche dev derive *`. (derive takes the
# record rather than calling model itself; cross-module composition is the
# run-body's job, not the library's.)

export const ENGINE_TYPE: string = "record<flags: table<snake: string, preserved: string, summary: string, state: oneof<nothing, record<default: bool, scope: list<string>>>>, syntax_rules: table<verb: string, object_slots: int, direct_preposition: oneof<string, nothing>, direct_required_flag: oneof<string, nothing>, direct_search_locations: list<string>, indirect_preposition: oneof<string, nothing>, indirect_required_flag: oneof<string, nothing>, indirect_search_locations: list<string>, action: string, pre_action: oneof<string, nothing>, games: list<int>>, syntax_verb_synonyms: table<verb: string, synonyms: list<string>, games: list<int>>, syntax_prepositions: table<preposition: string, synonyms: list<string>, games: list<int>>, syntax_directions: table<direction: string, synonyms: list<string>, games: list<int>>, syntax_buzzwords: table<word: string, games: list<int>>>"
export const CONDITIONS_TYPE: string = "table<snake: string, kind: string>"

# Write <out_dir>/engine.nu = `export const ENGINE: <ENGINE_TYPE> = <data>`. Idempotent.
export def derive_engine [
    engine: record<flags: table<snake: string, preserved: string, summary: string, state: oneof<nothing, record<default: bool, scope: list<string>>>>>,
    out_dir: directory
]: nothing -> record<written: string, flags: int> {
    let data = ($engine | to nuon --list-of-records --indent 2)
    let header = "# generated by arche:dev:derive - do not edit"
    let body = ([$header "" $"export const ENGINE: ($ENGINE_TYPE) = ($data)" ""] | str join (char nl))
    let dir = ($out_dir | path join "engine")
    mkdir $dir
    let path = ($dir | path join "mod.nu")
    $body | save -f $path
    {written: $path, flags: ($engine.flags | length)}
}

# Write <out_dir>/<episode>/conditions/mod.nu = `export const CONDITIONS: <type> = <data>`.
# Per-episode gate-kind dictionary; map data (rooms/links/blocked) is now per-file loader
# data (pelos data `room`), not a const. Idempotent.
export def derive_conditions [
    conditions: table<snake: string, kind: string>,
    episode: string,
    out_dir: directory
]: nothing -> record<written: string, conditions: int> {
    let data = ($conditions | to nuon --list-of-records --indent 2)
    let header = "# generated by arche:dev:derive - do not edit"
    let body = ([$header "" $"export const CONDITIONS: ($CONDITIONS_TYPE) = ($data)" ""] | str join (char nl))
    let dir = ($out_dir | path join $episode | path join "conditions")
    mkdir $dir
    let path = ($dir | path join "mod.nu")
    $body | save -f $path
    {written: $path, conditions: ($conditions | length)}
}

export const VOCABULARY_TYPE: string = "table<word: string, parts_of_speech: list<string>, verb: oneof<string, nothing>, preposition: oneof<string, nothing>, direction: oneof<string, nothing>>"

# Write <out_dir>/<episode>/vocabulary/mod.nu = `export const VOCABULARY: <type> = <data>`.
# Flat table (list<string> + oneof columns, no nested table column) - const-safe at the
# proven record>table depth (the world/grammar nesting lesson). Idempotent.
export def derive_vocabulary [
    vocabulary: table<word: string, parts_of_speech: list<string>, verb: oneof<string, nothing>, preposition: oneof<string, nothing>, direction: oneof<string, nothing>>,
    episode: string,
    out_dir: directory
]: nothing -> record<written: string, words: int> {
    let data = ($vocabulary | to nuon --list-of-records --indent 2)
    let header = "# generated by arche:dev:derive - do not edit"
    let body = ([$header "" $"export const VOCABULARY: ($VOCABULARY_TYPE) = ($data)" ""] | str join (char nl))
    let dir = ($out_dir | path join $episode | path join "vocabulary")
    mkdir $dir
    let path = ($dir | path join "mod.nu")
    $body | save -f $path
    {written: $path, words: ($vocabulary | length)}
}
